### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGSvgView

### ISSUE THREAD

**Issue by pauchiner** [gluestack/gluestack-ui-todos-example#2]
I don't know if is a problem with the proyect structure or with the gluestack-ui library it's self

## System Specs
- SO: Mac Os Ventura 13.4 (22F66)
- Package Manager: Yarn 1.22.19

## Steps to reproduce
1. clone the repo on local.
2. run `yarn install` inside the repository.
3. run `yarn start` and then `i` for the `Open iOs simulator` option.

> I tried running the web version and works perfectly.

This is the error that throws:
```
 ERROR  Invariant Violation: Tried to register two views with the same name RNSVGSvgView, js engine: hermes

 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes```

**Comment by ankit-tailor** [comment]
Hey @pauchiner, Thanks for reporting the issue. It is fixed.
